"""/ci-setup — Plugin setup, key management, local DB init.

Exit codes:
  0 — all ready
  2 — Python dependencies missing
  3 — required API keys missing (Gemini + Apify)
"""

from __future__ import annotations

import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent))

import argparse
import json
import os

from config import CONFIG_DIR, ENV_FILE, ensure_config_dir, get_settings

REQUIRED_DEPS = {
    "apify_client": "apify-client",
    "google.genai": "google-genai",
    "httpx": "httpx",
    "pydantic": "pydantic",
    "pydantic_settings": "pydantic-settings",
    "aiofiles": "aiofiles",
    "tenacity": "tenacity",
    "numpy": "numpy",
}


def check_deps() -> list[str]:
    missing = []
    for mod, pkg in REQUIRED_DEPS.items():
        try:
            __import__(mod)
        except ImportError:
            missing.append(pkg)
    return missing


def write_env_skeleton() -> None:
    """Scaffold ~/.config/content-intel/.env with placeholders."""
    ensure_config_dir()
    if ENV_FILE.exists():
        return
    ENV_FILE.write_text(
        """# Content Intelligence Plugin — Environment Variables
# Owner-only readable (chmod 600 on Unix)
# Generated by /ci-setup

# === Gemini (Google AI Studio) ===
# Required. Get key: https://aistudio.google.com/apikey
GEMINI_API_KEY=
GEMINI_MODEL_ANALYSIS=gemini-2.5-flash
GEMINI_MODEL_EMBEDDING=gemini-embedding-001
GEMINI_EMBEDDING_DIM=1536

# === Apify (Instagram + TikTok + YouTube + Google Maps scraping) ===
# Required. Get token: https://console.apify.com/account/integrations
APIFY_API_TOKEN=

# Instagram
APIFY_REEL_ACTOR=apify/instagram-reel-scraper
APIFY_BULK_ACTOR=apidojo/instagram-scraper
APIFY_PROFILE_ACTOR=apify/instagram-profile-scraper

# TikTok
APIFY_TIKTOK_ACTOR=clockworks/tiktok-scraper
APIFY_TIKTOK_ACTOR_FREE=clockworks/free-tiktok-scraper

# Future platforms (Phase 5+)
APIFY_YOUTUBE_ACTOR=streamers/youtube-scraper
APIFY_GMAPS_ACTOR=compass/crawler-google-places

# === User identity (for created_by audit) ===
# CI_USER=nayl

# === Optional Phase 6+ Supabase Team-Sync ===
# Leave empty if you only use SQLite locally
# SUPABASE_URL=
# SUPABASE_SERVICE_ROLE_KEY=
# SUPABASE_DB_URL=
""",
        encoding="utf-8",
    )
    try:
        os.chmod(ENV_FILE, 0o600)
    except (OSError, NotImplementedError):
        pass


def set_env_key(name: str, value: str) -> None:
    """Set or update a key in the .env file."""
    write_env_skeleton()
    lines = ENV_FILE.read_text(encoding="utf-8").splitlines()
    found = False
    for i, line in enumerate(lines):
        if line.startswith(f"{name}=") or line.startswith(f"# {name}="):
            lines[i] = f"{name}={value}"
            found = True
            break
    if not found:
        lines.append(f"{name}={value}")
    ENV_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")
    try:
        os.chmod(ENV_FILE, 0o600)
    except (OSError, NotImplementedError):
        pass


def init_local_db() -> dict:
    """Initialize the local SQLite DB. Returns stats."""
    from db.local_db import get_local_db
    db = get_local_db()
    return db.stats()


def status() -> dict:
    """Aggregate setup status."""
    deps = check_deps()
    write_env_skeleton()
    get_settings.cache_clear()
    s = get_settings()

    missing_required = []
    if not s.has_gemini():
        missing_required.append("GEMINI_API_KEY")
    if not s.has_apify():
        missing_required.append("APIFY_API_TOKEN")

    return {
        "missing_deps": deps,
        "missing_required_keys": missing_required,
        "config_file": str(ENV_FILE),
        "config_dir": str(CONFIG_DIR),
        "db_file": str(s.app_env and (CONFIG_DIR / "ci.db")),
        "has_gemini": s.has_gemini(),
        "has_apify": s.has_apify(),
        "has_supabase": s.has_supabase(),
        "tiktok_configured": bool(s.apify_tiktok_actor),
    }


def _prompt_for_missing_keys(missing: list[str]) -> None:
    """Interactively prompt the user for missing keys and store them.

    Uses stdin/getpass. If stdin is not a TTY (running from a script), skips
    prompts gracefully so the caller can still see the missing list.
    """
    import getpass
    if not sys.stdin.isatty():
        return

    URL_HINTS = {
        "GEMINI_API_KEY": "https://aistudio.google.com/apikey",
        "APIFY_API_TOKEN": "https://console.apify.com/account/integrations",
    }

    print()
    print("Interactive setup — enter values for missing keys (empty = skip).")
    print()
    for key in missing:
        hint = URL_HINTS.get(key, "")
        prompt_label = f"  {key}" + (f" ({hint})" if hint else "") + ": "
        try:
            value = getpass.getpass(prompt_label)
        except (KeyboardInterrupt, EOFError):
            print("\n[ci-setup] Cancelled.")
            return
        value = value.strip()
        if value:
            set_env_key(key, value)
            print(f"  [ok] saved {key}")
        else:
            print(f"  [skipped] {key}")


def main() -> int:
    parser = argparse.ArgumentParser(description="Content Intelligence Plugin Setup")
    parser.add_argument("--check", action="store_true", help="Silent check + exit code")
    parser.add_argument("--json", action="store_true", help="Machine-readable JSON output")
    parser.add_argument(
        "--set-key",
        nargs=2,
        metavar=("NAME", "VALUE"),
        help="Set an env key, e.g. --set-key GEMINI_API_KEY AIzaSy...",
    )
    parser.add_argument(
        "--interactive",
        action="store_true",
        help="Prompt for missing required keys (TTY only)",
    )
    args = parser.parse_args()

    if args.set_key:
        name, value = args.set_key
        set_env_key(name, value)
        print(f"[ci-setup] saved {name} -> {ENV_FILE}")
        return 0

    # Init local DB always (idempotent)
    db_init_error: str | None = None
    try:
        db_stats = init_local_db()
    except Exception as e:
        db_init_error = str(e)[:300]
        db_stats = {"error": db_init_error}

    s = status()
    if db_init_error:
        # Surface DB init failure as a missing-deps style problem so exit code != 0
        s.setdefault("missing_deps", []).append(f"local-db-init: {db_init_error[:100]}")

    if args.json:
        s["db_stats"] = db_stats
        print(json.dumps(s, indent=2))
        return 0 if (not s["missing_deps"] and not s["missing_required_keys"]) else 1

    if args.check:
        if s["missing_deps"]:
            return 2
        if s["missing_required_keys"]:
            return 3
        return 0

    # Human-readable
    print(f"[ci-setup] Config: {ENV_FILE}")
    print(f"[ci-setup] Local DB: {CONFIG_DIR / 'ci.db'}")
    print()

    if s["missing_deps"]:
        print("MISSING DEPENDENCIES:")
        for pkg in s["missing_deps"]:
            print(f"  - {pkg}")
        print()
        print("Install with:")
        print(f"  python -m pip install --user {' '.join(s['missing_deps'])}")
        print()

    if s["missing_required_keys"]:
        print("MISSING REQUIRED KEYS:")
        for k in s["missing_required_keys"]:
            print(f"  - {k}")
        print()
        print("Get keys at:")
        print("  Gemini:  https://aistudio.google.com/apikey  (free tier OK)")
        print("  Apify:   https://console.apify.com/account/integrations")
        print()
        if args.interactive:
            _prompt_for_missing_keys(s["missing_required_keys"])
            # Re-evaluate after interactive prompts
            get_settings.cache_clear()
            s = status()
        else:
            print("Quickest fix:")
            print(f'  python "{Path(__file__)}" --interactive')
            print()
            print("Or set keys individually:")
            print(f'  python "{Path(__file__)}" --set-key GEMINI_API_KEY AIzaSy...')
            print(f'  python "{Path(__file__)}" --set-key APIFY_API_TOKEN apify_api_xxx')
            print()

    if not s["missing_deps"] and not s["missing_required_keys"]:
        print("READY — Gemini + Apify configured")
        print()
        if "error" not in db_stats:
            print(f"Local DB: {db_stats.get('db_size_mb', 0)} MB")
            print(f"  Clients: {db_stats.get('clients_total', 0)}")
            print(f"  Reels:   {db_stats.get('reels_total', 0)}")
            print(f"  Scripts: {db_stats.get('scripts_total', 0)}")
        print()
        print("Next steps:")
        print("  /ci-client-add <name>      — create a client profile")
        print("  /ci-analyze <url>          — analyze a reel")
        print("  /ci-status                 — view dashboard")
        print()
        if not s["has_supabase"]:
            print("Note: Supabase team-sync NOT configured (optional, Phase 6+).")
            print("      All data lives locally in ~/.config/content-intel/ci.db")

    if s["missing_deps"] or s["missing_required_keys"]:
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
